apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.env.appPort }}
      nodePort: {{ .Values.web.service.nodePort }}
      targetPort: {{ .Values.web.env.appPort }}
