apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: db
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.project }}/{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
