apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.authApi.env.appPort }}
      targetPort: {{ .Values.authApi.env.appPort }}
