apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  {{- if not .Values.authApi.hpa.enabled }}
  replicas: {{ .Values.authApi.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: auth-api-container
          image: "{{ .Values.harbor.host }}/{{ .Values.authApi.image.repository }}:{{ .Values.authApi.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.authApi.resources.requests.cpu }}
              memory: {{ .Values.authApi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.authApi.resources.limits.cpu }}
              memory: {{ .Values.authApi.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.authApi.env.appPort }}
          env:
            - name: APP_PORT
              value: "{{ .Values.authApi.env.appPort }}"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-api-secret
                  key: APP_SECRET
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
