apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: {{- .Release.Namespace -}}
spec:
  replicas: {{- .Values.authApi.replicas -}}
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: auth-api-container
          image: "{{- .Values.harbor.secret.host -}}/{{- .Values.authApi.image.repository -}}:{{- .Values.authApi.image.tag -}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{- .Values.authApi.env.appPort -}}
          env:
            - name: APP_PORT
              value: "{{- .Values.authApi.env.appPort -}}"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-apui-secret
                  key: APP_SECRET
            - name: DB_HOST
              value: db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
