apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{- .Values.db.secret.user | b64enc | quote -}}
  POSTGRES_PASSWORD: {{- .Values.db.secret.password | b64enc | quote -}}
  POSTGRES_DB: {{- .Values.db.secret.db | b64enc | quote -}}
