apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "termdo.componentName" (dict "root" . "component" "db") }}-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.db.pvc.storage }}
