apiVersion: v1
kind: Service
metadata:
  name: gateway-api
spec:
  selector:
    app: gateway-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.gatewayApi.env.appPort }}
      targetPort: {{ .Values.gatewayApi.env.appPort }}
      nodePort: {{ .Values.gatewayApi.service.nodePort }}
