apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.harbor.host }}": {
          "username": "{{ .Values.harbor.secret.name }}",
          "password": "{{ .Values.harbor.secret.token }}",
          "auth": "{{ printf "%s:%s" .Values.harbor.secret.name .Values.harbor.secret.token | b64enc }}"
        }
      }
    }
