apiVersion: v1
kind: Service
metadata:
  name: tasks-api-service
  namespace: {{- .Release.Namespace -}}
spec:
  selector:
    app: tasks-api
  type: ClusterIP
  ports:
    - port: {{- .Values.tasksApi.env.appPort -}}
      targetPort: {{- .Values.tasksApi.env.appPort -}}
      protocol: TCP
      name: http
