apiVersion: v1
kind: Service
metadata:
  name: tasks-api
spec:
  selector:
    app: tasks-api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.tasksApi.env.appPort }}
      targetPort: {{ .Values.tasksApi.env.appPort }}
