apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api-deployment
spec:
  {{- if not .Values.tasksApi.hpa.enabled }}
  replicas: {{ .Values.tasksApi.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: tasks-api-container
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.project }}/{{ .Values.tasksApi.image.repository }}:{{ .Values.tasksApi.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.tasksApi.resources.requests.cpu }}
              memory: {{ .Values.tasksApi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.tasksApi.resources.limits.cpu }}
              memory: {{ .Values.tasksApi.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.tasksApi.env.appPort }}
          env:
            - name: APP_PORT
              value: "{{ .Values.tasksApi.env.appPort }}"
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
